### ISSUE TITLE
Exception occurred deleting files.

### ISSUE THREAD

**Issue by zihuq-msft** [Azure-Samples/chat-with-your-data-solution-accelerator#1091]
# Describe the bug
When trying to load the 'Delete Data' page in admin panel, error message shows up instead of list of files

# Expected behavior
list of files that have been ingested and processed that can be selected for deletion.

# How does this bug make you feel?
_Share a gif from [giphy](https://giphy.com/) to tells us how you'd feel_
![image](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTVlNWdhYmp2bXcxMm1wdjRzZXRpbjA5dDgxYm9tYW01ZGgzYWpmNCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/kPtv3UIPrv36cjxqLs/giphy.gif)

# Debugging information

## Steps to reproduce
1. Load Admin Panel
2. Upload some file for processing
3. Click on 'Delete Data'

## Screenshots
![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/171873061/11c761b6-a73f-452e-aca2-370f1411a3de)

## Logs
2024-06-26T18:30:27.8770453Z 2024-06-26 18:30:27.876 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
2024-06-26T18:30:27.8839802Z ERROR:__main__:Traceback (most recent call last):
2024-06-26T18:30:27.8840348Z   File "/tmp/8dc96093d74bd8b/pages/03_Delete_Data.py", line 53, in <module>
2024-06-26T18:30:27.8840397Z     selections = {
2024-06-26T18:30:27.8840432Z                  ^
2024-06-26T18:30:27.8840470Z   File "/tmp/8dc96093d74bd8b/pages/03_Delete_Data.py", line 54, in <dictcomp>
2024-06-26T18:30:27.8840506Z     filename: st.checkbox(filename, False, key=filename)
2024-06-26T18:30:27.8840576Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-26T18:30:27.8840619Z   File "/tmp/8dc96093d74bd8b/antenv/lib/python3.11/site-packages/streamlit/runtime/metrics_util.py", line 408, in wrapped_func
2024-06-26T18:30:27.8840654Z     result = non_optional_func(*args, **kwargs)
2024-06-26T18:30:27.8840689Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-26T18:30:27.8840731Z   File "/tmp/8dc96093d74bd8b/antenv/lib/python3.11/site-packages/streamlit/elements/widgets/checkbox.py", line 149, in checkbox
2024-06-26T18:30:27.8840767Z     return self._checkbox(
2024-06-26T18:30:27.8840800Z            ^^^^^^^^^^^^^^^
2024-06-26T18:30:27.8840840Z   File "/tmp/8dc96093d74bd8b/antenv/lib/python3.11/site-packages/streamlit/elements/widgets/checkbox.py", line 307, in _checkbox
2024-06-26T18:30:27.8840894Z     checkbox_proto.label = label
2024-06-26T18:30:27.8840929Z     ^^^^^^^^^^^^^^^^^^^^
2024-06-26T18:30:27.8840964Z TypeError: bad argument type for built-in operation
2024-06-26T18:30:27.8841002Z
---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by Roopan-Microsoft** [comment]
@zihuq-msft - Please check if you have document which got processed with title as NULL as mentioned below,
<img width="509" alt="image" src="https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/168007406/6cea55d5-fefd-44a3-a5a4-e757ee64e25a">

If yes, please remove that particular document from storage account and click 'Reprocess' from the Ingest data page.

**Comment by Avijit-Microsoft** [comment]
@zihuq-msft - Please put your comment if you need any further support for this issue.
