### ISSUE TITLE
Error while setting advanced image processing on ['jpeg', 'jpg', 'png', 'tiff', 'bmp']

### ISSUE THREAD

**Issue by yaowilli** [Azure-Samples/chat-with-your-data-solution-accelerator#1250]
# Describe the bug
While the documentation (https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/advanced_image_processing.md ) states that Advanced image processing can be done for ['jpeg', 'jpg', 'png', 'tiff', 'bmp'] , however configuring in the admin app the advanced image processing i do get the following errors:
Traceback (most recent call last): File "/tmp/8dcb7fb38d2a08c/pages/04_Configuration.py", line 404, in <module> ConfigHelper.save_config_as_active(current_config) File "/tmp/8dcb7fb38d2a08c/batch/utilities/helpers/config/config_helper.py", line 204, in save_config_as_active ConfigHelper.validate_config(config) File "/tmp/8dcb7fb38d2a08c/batch/utilities/helpers/config/config_helper.py", line 224, in validate_config raise Exception( Exception: Advanced image processing has been enabled for document type pdf, but only ['jpeg', 'jpg', 'png', 'tiff', 'bmp'] file types are supported. 

# Expected behavior
please see link : (https://github.com/Azure-Samples/chat-with-your-data-solutionaccelerator/blob/main/docs/advanced_image_processing.md ) 

# How does this bug make you feel?
it is an issue/bug 

---
![image](https://github.com/user-attachments/assets/6a4627db-d923-4f9d-97ea-6df612486193)

# Debugging information

## Steps to reproduce
just attempt to configure advanced image processing in the Admin App as showing on the attachment to this issue

**Comment by Roopan-Microsoft** [comment]
Hi @yaowilli - Thanks for raising this issue. We are looking into this. Will keep you posted.

We will handle this error accordingly. Thanks

**Comment by Roopan-Microsoft** [comment]
We have handled that exception accordingly. 

Also Advanced image processing is applicable only for ['jpeg', 'jpg', 'png', 'tiff', 'bmp'] as mentioned in the document. User will get the friendly message now.

PR has merged a spart of #1291.

I’m closing this ticket now. If you encounter any new issues, don’t hesitate to open another one.

Happy to assist!
