### ISSUE TITLE
The managed identity configuration is invalid: Managed identity is not enabled for the current resource -- Document Intelligence

### ISSUE THREAD

**Issue by jmasengeshomsft** [Azure-Samples/chat-with-your-data-solution-accelerator#1391]
# Describe the bug
The application does not process new documents successfully when AI services are private endpoints enabled.
See the error bellow, its logged in Application Insights:

------------------

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/opentelemetry/trace/__init__.py", line 590, in use_span
    yield span
  File "/usr/local/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 105, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/ai/formrecognizer/_document_analysis_client.py", line 198, in begin_analyze_document_from_url
    return _client_op_path.begin_analyze_document(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 105, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/ai/formrecognizer/_generated/v2023_07_31/operations/_document_models_operations.py", line 518, in begin_analyze_document
    raw_result = self._analyze_document_initial(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/ai/formrecognizer/_generated/v2023_07_31/operations/_document_models_operations.py", line 443, in _analyze_document_initial
    raise HttpResponseError(response=response)
azure.core.exceptions.HttpResponseError: (InvalidRequest) Invalid request.
Code: InvalidRequest
Message: Invalid request.
Inner error: {
    "code": "InvalidManagedIdentity",
    "message": "The managed identity configuration is invalid: Managed identity is not enabled for the current resource."
}

**Comment by Roopan-Microsoft** [comment]
Hi @jmasengeshomsft - Thanks for your feedback, We are investigating the issue from our end.

Based on the exception, we see its failing for Azure Form Recognizer resource. Will keep you posted.

**Comment by Prasanjeet-Microsoft** [comment]
Hello @jmasengeshomsft , Could you please provide the steps to reproduce this issue? This will help us identify and troubleshoot it more effectively.

**Comment by Vinay-Microsoft** [comment]
Hi @jmasengeshomsft this is an enhancement request no private endpoint in CWYD accelerator. So changing it from bug to enhancement request
