### ISSUE TITLE
deploy postgresql type always create AI search, delete the search instance then the frontend webapp report error

### ISSUE THREAD

**Issue by cyberflying** [Azure-Samples/chat-with-your-data-solution-accelerator#1600]
# Describe the bug
When choose pg, the deployment always create a AI search.
If delete the search service,  chat web app will report error.
![image](https://github.com/user-attachments/assets/4b649f13-190f-430a-affd-491a30d081ee)

It seems will create an AI search index "conversation" when chat with the webapp, and then report error in logs:
![image](https://github.com/user-attachments/assets/85c99c86-6d6b-4346-b9f8-7bc47a8f5be6)

# Expected behavior
In architecture with pg, never use AI search, I think don't need to create an AI search when deploy.

# How does this bug make you feel?
_Share a gif from [giphy](https://giphy.com/) to tells us how you'd feel_

---

# Debugging information

## Steps to reproduce
1. deploy with PG option
2. check the AI search index
3. delete the AI search
4. chat with webapp

## Logs
`2024-12-27T16:20:14.3376300Z ERROR:create_app:Exception in /api/conversation | Operation returned an invalid status 'Forbidden'
2024-12-27T16:20:14.3376916Z Traceback (most recent call last):
2024-12-27T16:20:14.3377022Z File "/usr/src/app/create_app.py", line 444, in conversation_custom
2024-12-27T16:20:14.3377060Z messages = await message_orchestrator.handle_message(
2024-12-27T16:20:14.3377091Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-27T16:20:14.3377127Z File "/usr/src/app/backend/batch/utilities/helpers/orchestrator_helper.py", line 22, in handle_message
2024-12-27T16:20:14.3377159Z orchestrator = get_orchestrator(orchestrator.strategy.value)
2024-12-27T16:20:14.3377191Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-27T16:20:14.3377225Z File "/usr/src/app/backend/batch/utilities/orchestrator/strategies.py", line 14, in get_orchestrator
2024-12-27T16:20:14.3377257Z return SemanticKernelOrchestrator()
2024-12-27T16:20:14.3377287Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-27T16:20:14.3377341Z File "/usr/src/app/backend/batch/utilities/orchestrator/semantic_kernel.py", line 21, in __init__
2024-12-27T16:20:14.3377378Z super().__init__()
2024-12-27T16:20:14.3377414Z File "/usr/src/app/backend/batch/utilities/orchestrator/orchestrator_base.py", line 20, in __init__
2024-12-27T16:20:14.3377450Z self.conversation_logger: ConversationLogger = ConversationLogger()
2024-12-27T16:20:14.3377482Z ^^^^^^^^^^^^^^^^^^^^
2024-12-27T16:20:14.3377516Z File "/usr/src/app/backend/batch/utilities/loggers/conversation_logger.py", line 8, in __init__
2024-12-27T16:20:14.3377548Z self.logger = AzureSearchHelper().get_conversation_logger()
2024-12-27T16:20:14.3377580Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-27T16:20:14.3377643Z File "/usr/src/app/backend/batch/utilities/helpers/azure_search_helper.py", line 268, in get_conversation_logger
2024-12-27T16:20:14.3377673Z return AzureSearch(
2024-12-27T16:20:14.3377701Z ^^^^^^^^^^^^
2024-12-27T16:20:14.3377736Z File "/usr/local/lib/python3.11/site-packages/langchain_community/vectorstores/azuresearch.py", line 335, in __init__
2024-12-27T16:20:14.3377767Z self.client = _get_search_client(
2024-12-27T16:20:14.3377797Z ^^^^^^^^^^^^^^^^^^^
2024-12-27T16:20:14.3377836Z File "/usr/local/lib/python3.11/site-packages/langchain_community/vectorstores/azuresearch.py", line 145, in _get_search_client
2024-12-27T16:20:14.3377868Z index_client.get_index(name=index_name)
2024-12-27T16:20:14.3377903Z File "/usr/local/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 105, in wrapper_use_tracer
2024-12-27T16:20:14.3377948Z return func(*args, **kwargs)
2024-12-27T16:20:14.3377979Z ^^^^^^^^^^^^^^^^^^^^^
2024-12-27T16:20:14.3378015Z File "/usr/local/lib/python3.11/site-packages/azure/search/documents/indexes/_search_index_client.py", line 149, in get_index
2024-12-27T16:20:14.3378046Z result = self._client.indexes.get(name, **kwargs)
2024-12-27T16:20:14.3378078Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-27T16:20:14.3378112Z File "/usr/local/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 105, in wrapper_use_tracer
2024-12-27T16:20:14.3378142Z return func(*args, **kwargs)
2024-12-27T16:20:14.3378171Z ^^^^^^^^^^^^^^^^^^^^^
2024-12-27T16:20:14.3378208Z File "/usr/local/lib/python3.11/site-packages/azure/search/documents/indexes/_generated/operations/_indexes_operations.py", line 866, in get
2024-12-27T16:20:14.3378261Z raise HttpResponseError(response=response, model=error)
2024-12-27T16:20:14.3378297Z azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Forbidden'
2024-12-27T16:20:14.3441165Z [pid: 1|app: 0|req: 59/59] 169.254.129.2 () {102 vars in 10187 bytes} [Fri Dec 27 16:20:13 2024] POST /api/conversation => generated 113 bytes in 768 msecs (HTTP/1.1 500) 2 headers in 91 bytes (1 switches on core 0)
2024-12-27T16:20:14.4986780Z INFO:backend.batch.utilities.helpers.config.config_helper:Returning default config
2024-12-27T16:20:14.5009769Z [pid: 1|app: 0|req: 60/60] 169.254.129.2 () {100 vars in 10125 bytes} [Fri Dec 27 16:20:14 2024] GET /api/assistanttype => generated 32 bytes in 159 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
2024-12-27T16:20:46.4079721Z INFO:backend.batch.utilities.helpers.config.config_helper:Returning default config
2024-12-27T16:20:46.4088040Z [pid: 1|app: 0|req: 61/61] 169.254.129.2 () {100 vars in 10125 bytes} [Fri Dec 27 16:20:46 2024] GET /api/assistanttype => generated 32 bytes in 154 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
2024-12-27T16:20:58.8123994Z [pid: 1|app: 0|req: 62/62] 169.254.129.2 () {40 vars in 788 bytes} [Fri Dec 27 16:20:58 2024] GET /api/health => generated 2 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 78 bytes (1 switches on core 0)`
---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by Prasanjeet-Microsoft** [comment]
Hello @cyberflying, Thank you for reporting this issue! We appreciate your feedback, and we will start investigating the issue and keep you updated on our progress.

**Comment by Prasanjeet-Microsoft** [comment]
Hello @cyberflying, Could you please confirm if you have deployed this accelerator with the auth type set to keys or rbac and whether this error is occurring on the server or locally?

**Comment by cyberflying** [comment]
Hi @Prasanjeet-Microsoft , I choose RBAC,  the screenshot shows the chat webapp error logs in "deployment center" page "logs" tab.

**Comment by Prasanjeet-Microsoft** [comment]
Hello @cyberflying, Thank you for your prompt response. I just wanted to inform you that this part was left as part of the enhancement, and we were already aware of it. We are currently working on it and will update you once it's completed.

**Comment by cyberflying** [comment]
Hi @Prasanjeet-Microsoft , thank you for your update. We will have a version following the PG architecture diagram, right? Meaning doesn't require AI search.

**Comment by Prasanjeet-Microsoft** [comment]
> Hi @Prasanjeet-Microsoft , thank you for your update. We will have a version following the PG architecture diagram, right? Meaning doesn't require AI search.

Yes, that's correct.

**Comment by Prasanjeet-Microsoft** [comment]
Hello @cyberflying, I wanted to let you know that we are currently addressing this issue and are working on a resolution. We will keep you informed and notify you once everything is completed.

Thank you.

**Comment by Prasanjeet-Microsoft** [comment]
Hello @cyberflying, We are currently working on resolving this issue and will keep you updated on the progress. We will notify you once everything is completed.

**Comment by Prasanjeet-Microsoft** [comment]
Hello @cyberflying, This is just to give you a heads-up that we are actively working to resolve this issue and will keep you informed on our progress. You will be notified as soon as everything is completed.

**Comment by Prasanjeet-Microsoft** [comment]
Hello @cyberflying, Just to keep you updated, we are now in the testing phase of resolving this issue. We expect to release the functionality shortly and will notify you as soon as it's ready.

Thank you.

**Comment by Prasanjeet-Microsoft** [comment]
> It's great, thanks for keeping updated.

@cyberflying, Thank you for your patience. We are planning to release this functionality in the next 1 or 2 days. We will notify you as soon as it's available.

**Comment by Prasanjeet-Microsoft** [comment]
Hello @cyberflying, We have released the mentioned functionality and resolved this issue. Could you please try deploying the accelerator with the PostgreSQL database type and let us know the results?

Thank you.

**Comment by cyberflying** [comment]
Hi @Prasanjeet-Microsoft ,
I just deployed and tested it, and it worked. Thank you!
