### ISSUE TITLE
ImportError: cannot import name 'ExhaustiveKnnAlgorithmConfiguration' from 'azure.search.documents.indexes.models'

### ISSUE THREAD

**Issue by luislofer89** [Azure-Samples/chat-with-your-data-solution-accelerator#314]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Deploy the solution using One-Click deployment
>Wait until solution is completely deployed
>Use front-end chatbot interface
>ImportError: cannot import name 'ExhaustiveKnnAlgorithmConfiguration' from 'azure.search.documents.indexes.models'

### Any log messages given by the failure
>2024-02-21T07:48:14.487565121Z: [ERROR]  Traceback (most recent call last):
2024-02-21T07:48:14.487571422Z: [ERROR]    File "app.py", line 342, in conversation_custom
2024-02-21T07:48:14.487576222Z: [ERROR]      messages = message_orchestrator.handle_message(
2024-02-21T07:48:14.487580722Z: [ERROR]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-21T07:48:14.487585023Z: [ERROR]    File "/usr/src/app/utilities/helpers/OrchestratorHelper.py", line 20, in handle_message
2024-02-21T07:48:14.487589723Z: [ERROR]      orchestrator = get_orchestrator(orchestrator.strategy.value)
2024-02-21T07:48:14.487594124Z: [ERROR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-21T07:48:14.487598424Z: [ERROR]    File "/usr/src/app/utilities/orchestrator/Strategies.py", line 13, in get_orchestrator
2024-02-21T07:48:14.487603024Z: [ERROR]      return OpenAIFunctionsOrchestrator()
2024-02-21T07:48:14.487608025Z: [ERROR]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-21T07:48:14.487612625Z: [ERROR]    File "/usr/src/app/utilities/orchestrator/OpenAIFunctions.py", line 16, in __init__
2024-02-21T07:48:14.487617126Z: [ERROR]      super().__init__()
2024-02-21T07:48:14.487621426Z: [ERROR]    File "/usr/src/app/utilities/orchestrator/OrchestratorBase.py", line 18, in __init__
2024-02-21T07:48:14.487625926Z: [ERROR]      self.conversation_logger: ConversationLogger = ConversationLogger()
2024-02-21T07:48:14.487630827Z: [ERROR]                                                     ^^^^^^^^^^^^^^^^^^^^
2024-02-21T07:48:14.487635427Z: [ERROR]    File "/usr/src/app/utilities/loggers/ConversationLogger.py", line 8, in __init__
2024-02-21T07:48:14.487640027Z: [ERROR]      self.logger = AzureSearchHelper().get_conversation_logger()
2024-02-21T07:48:14.487644428Z: [ERROR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-21T07:48:14.487648728Z: [ERROR]    File "/usr/src/app/utilities/helpers/AzureSearchHelper.py", line 140, in get_conversation_logger
2024-02-21T07:48:14.487653429Z: [ERROR]      return AzureSearch(
2024-02-21T07:48:14.487657729Z: [ERROR]             ^^^^^^^^^^^^
2024-02-21T07:48:14.487661929Z: [ERROR]    File "/usr/local/lib/python3.11/site-packages/langchain_community/vectorstores/azuresearch.py", line 268, in __init__
2024-02-21T07:48:14.487666530Z: [ERROR]      self.client = _get_search_client(
2024-02-21T07:48:14.487670930Z: [ERROR]                    ^^^^^^^^^^^^^^^^^^^
2024-02-21T07:48:14.487675330Z: [ERROR]    File "/usr/local/lib/python3.11/site-packages/langchain_community/vectorstores/azuresearch.py", line 84, in _get_search_client
2024-02-21T07:48:14.487679831Z: [ERROR]      from azure.search.documents.indexes.models import (
2024-02-21T07:48:14.487685231Z: [ERROR]  ImportError: cannot import name 'ExhaustiveKnnAlgorithmConfiguration' from 'azure.search.documents.indexes.models' (/usr/local/lib/python3.11/site-packages/azure/search/documents/indexes/models/__init__.py)
2024-02-21T07:48:14.488613509Z: [ERROR]  [pid: 1|app: 0|req: 14/14] 169.254.131.1 () {86 vars in 1918 bytes} [Wed Feb 21 07:48:14 2024] POST /api/conversation/custom => generated 77 bytes in 308 msecs (HTTP/1.1 500) 2 headers in 90 bytes (1 switches on core 0)

### Expected/desired behavior
> The chatbot provides a response in the frontend

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ross-p-smith** [comment]
Can reproduce . . .

**Comment by ross-p-smith** [comment]
Hey @luislofer89 I have just merged another change that moves away from containers and deploys the python code directly to the App Service. Could you deploy using https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator?tab=readme-ov-file#running-the-sample-using-the-azure-developer-cli-azd and let me know if you get better success?

**Comment by AndTraHTI** [comment]
I have the same problem on an environment that was deployed a few weeks ago. Maybe a component in the latest version is causing the problem?

**Comment by ross-p-smith** [comment]
The new version of the code will NOT be using containers.

**Comment by luislofer89** [comment]
It works after the merge using adz
