### ISSUE TITLE
Admin Site Broke : Traceback - in _checkbox checkbox_proto.label = label

### ISSUE THREAD

**Issue by delicpsyche** [Azure-Samples/chat-with-your-data-solution-accelerator#372]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
- Navigate to the Admin site , go the Delete Sourcefile from Index Page .
-  Scroll down , the Delete Button is gone and you get a traceback

### Any log messages given by the failure
Traceback on GUI
`
Traceback (most recent call last): File "E:\BYUGD\src\pages\03_Delete.py", line 87, in <module> files = output_results(results) ^^^^^^^^^^^^^^^^^^^^^^^ File "E:\BYUGD\src\pages\03_Delete.py", line 58, in output_results st.checkbox(filename, False, key=filename) File "E:\BYUGD\venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 367, in wrapped_func result = non_optional_func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\BYUGD\venv\Lib\site-packages\streamlit\elements\widgets\checkbox.py", line 142, in checkbox return self._checkbox( ^^^^^^^^^^^^^^^ File "E:\BYUGD\venv\Lib\site-packages\streamlit\elements\widgets\checkbox.py", line 295, in _checkbox checkbox_proto.label = label ^^^^^^^^^^^^^^^^^^^^ TypeError: bad argument type for built-in operation
`
Errors on Console
`
19:41:41.080  'label' got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed
`

### Expected/desired behavior
You should get a Delete Button to delete the Sourcefiles from the Search Index

### OS and Version?
 Win 11 and Win 10

### Versions
Python runtime 3.10 on App Service
streamlit==1.27.1
python 3.10,3,11 on WinOS for local testing.

### Mention any other details that might be useful

This was working for 2-3 months , just broke a week ago.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ross-p-smith** [comment]
Can you retry with Python 3.11 please? This repo does not support Python 3.10

**Comment by delicpsyche** [comment]
Actually I did , as my local environment is 3.11.5 - same results.
