### ISSUE TITLE
Admin Site Web App not working after deploying code into Azure

### ISSUE THREAD

**Issue by sreedharguda** [Azure-Samples/chat-with-your-data-solution-accelerator#373]
Please find the below error message which am getting.   2024-03-04T04:41:20.925262850Z Documentation: http://aka.ms/webapp-linux
2024-03-04T04:41:20.925266450Z Python 3.11.4
2024-03-04T04:41:20.925269950Z Note: Any data outside '/home' is not persisted
2024-03-04T04:41:50.072947702Z Starting OpenBSD Secure Shell server: sshd.
2024-03-04T04:41:50.525420629Z Site's appCommandLine: python -m streamlit run Admin.py --server.port 8000 --server.address 0.0.0.0 --server.enableXsrfProtection false
2024-03-04T04:41:50.532551653Z Launching oryx with: create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv -defaultApp /opt/defaultsite -userStartupCommand 'python -m streamlit run Admin.py --server.port 8000 --server.address 0.0.0.0 --server.enableXsrfProtection false'
2024-03-04T04:41:50.805319774Z Could not find build manifest file at '/home/site/wwwroot/oryx-manifest.toml'
2024-03-04T04:41:50.811788596Z Could not find operation ID in manifest. Generating an operation id...
2024-03-04T04:41:50.821515029Z Build Operation ID: 5081fd40-a8d9-4ca1-9dbf-5c721222cef9
2024-03-04T04:41:51.874512183Z Oryx Version: 0.2.20230707.1, Commit: 0bd28e69919b5e8beba451e8677e3345f0be8361, ReleaseTagName: 20230707.1
2024-03-04T04:41:51.885344420Z Writing output script to '/opt/startup/startup.sh'
2024-03-04T04:41:51.936363192Z WARNING: Could not find virtual environment directory /home/site/wwwroot/antenv.
2024-03-04T04:41:51.936473792Z WARNING: Could not find package directory /home/site/wwwroot/__oryx_packages__.
2024-03-04T04:41:52.345043871Z /opt/python/3/bin/python: No module named streamlit

g warmup request to container xx-groupii-website-erndmgle2f4ma-admin_0_dff2a433_msiProxy for site xx-groupii-website-erndmgle2f4ma-admin
2024-03-04T04:41:31.936Z INFO  - Container xx-groupii-website-erndmgle2f4ma-admin_0_dff2a433_msiProxy for site xx-groupii-website-erndmgle2f4ma-admin initialized successfully and is ready to serve requests.
2024-03-04T04:41:31.937Z INFO  - Initiating warmup request to container xx-groupii-website-erndmgle2f4ma-admin_0_dff2a433 for site xx-groupii-website-erndmgle2f4ma-admin
2024-03-04T04:41:52.852Z INFO  - Waiting for response to warmup request for container xx-groupii-website-erndmgle2f4ma-admin_0_dff2a433. Elapsed time = 21.3431226 sec
2024-03-04T04:41:54.625Z ERROR - Container xx-groupii-website-erndmgle2f4ma-admin_0_dff2a433 for site xx-groupii-website-erndmgle2f4ma-admin has exited, failing site start
2024-03-04T04:41:54.627Z INFO  - Initiating warmup request to container xx-groupii-website-erndmgle2f4ma-admin_0_dff2a433_middleware for site xx-groupii-website-erndmgle2f4ma-admin
2024-03-04T04:42:04.022Z INFO  - Container xx-groupii-website-erndmgle2f4ma-admin_0_dff2a433_middleware for site xx-groupii-website-erndmgle2f4ma-admin initialized successfully and is ready to serve requests.
2024-03-04T04:42:04.112Z ERROR - Container xx-groupii-website-erndmgle2f4ma-admin_0_dff2a433 didn't respond to HTTP pings on port: 8000, failing site start. See container logs for debugging.
2024-03-04T04:42:04.227Z INFO  - Stopping site xx-groupii-website-erndmgle2f4ma-admin because it failed during startup.

**Comment by ross-p-smith** [comment]
Hi @sreedharguda - were you running this in a devcontainer / code spaces or natively on your linux machine?

**Comment by cherifbenham** [comment]
running this in a devcontainer and seeing the same logs

**Comment by sreedharguda** [comment]
> Hi @sreedharguda - were you running this in a devcontainer / code spaces or natively on your linux machine?

Hi @ross-p-smith , Yes, am doing this deployment in Azure subscription by using infra deployment under the docs folder (https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/INFRA_DEPLOYMENT.md). I used the linux container in web apps. Thank you.

**Comment by ross-p-smith** [comment]
Hi @sreedharguda - the accelerator doesn't use the docker images anymore. (I know that they are incorrectly in the repo at this point). The happy path of installing this is to use `azd up` from the devcontainer. I will delete everything, clone and see if this works

**Comment by ross-p-smith** [comment]
> running this in a devcontainer and seeing the same logs

Are you also building and deploying docker images to the app service or are you using either `azd up` or `az deploy web` / `az deploy adminweb` / `az deploy function`?

**Comment by sreedharguda** [comment]
> > running this in a devcontainer and seeing the same logs
> 
> Are you also building and deploying docker images to the app service or are you using either `azd up` or `az deploy web` / `az deploy adminweb` / `az deploy function`?

Hi @ross-p-smith am deploying this accelerator by using the Deploy to Azure Option (https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/ross/removeDocker/docs/INFRA_DEPLOYMENT.md). Please suggest me which one have to follow to build this solution in Azure env.

**Comment by ross-p-smith** [comment]
Thanks @sreedharguda. The easiest way is to simply use `azd auth login` and then `azd up`.
https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator?tab=readme-ov-file#deploy-instructions

You may be able to use `azd env` command to reuse your previous deployment - but I have never tried this. I know it's a pain, but you are much better deleting the deployment you previously created with ARM and using `azd` instead. This will generate you an .env file and allow you to debug locally more easily.

**Comment by sreedharguda** [comment]
> Thanks @sreedharguda. The easiest way is to simply use `azd auth login` and then `azd up`. https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator?tab=readme-ov-file#deploy-instructions
> 
> You may be able to use `azd env` command to reuse your previous deployment - but I have never tried this. I know it's a pain, but you are much better deleting the deployment you previously created with ARM and using `azd` instead. This will generate you an .env file and allow you to debug locally more easily.

Hi @ross-p-smith , Thank you for your response, have tried that method but am getting this error while running the docker.

https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/tree/ross/removeDocker?tab=readme-ov-file 
Start Docker Desktop (install it if not already installed)

Open the project: Open in Dev Containers

In the VS Code window that opens, once the project files show up (this may take several minutes), open a terminal window


#0 17.37 ERROR: Feature "Docker (docker-outside-of-docker)" (ghcr.io/devcontainers/features/docker-outside-of-docker) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/docker-outside-of-docker for help troubleshooting this error.
------
Dockerfile.extended:50
--------------------
  49 |     
  50 | >>> RUN --mount=type=bind,from=dev_containers_feature_content_source,source=docker-outside-of-docker_2,target=/tmp/build-features-src/docker-outside-of-docker_2 \
  51 | >>>     cp -ar /tmp/build-features-src/docker-outside-of-docker_2 /tmp/dev-container-features \
  52 | >>>  && chmod -R 0755 /tmp/dev-container-features/docker-outside-of-docker_2 \
  53 | >>>  && cd /tmp/dev-container-features/docker-outside-of-docker_2 \
  54 | >>>  && chmod +x ./devcontainer-features-install.sh \
  55 | >>>  && ./devcontainer-features-install.sh \
  56 | >>>  && rm -rf /tmp/dev-container-features/docker-outside-of-docker_2
  57 |     
--------------------
error: failed to solve: process "/bin/sh -c cp -ar /tmp/build-features-src/docker-outside-of-docker_2 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/docker-outside-of-docker_2  && cd /tmp/dev-container-features/docker-outside-of-docker_2  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/docker-outside-of-docker_2" did not complete successfully: exit code: 1
[144690 ms] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.56.2-1709566001811 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/python:1-3.11-bullseye --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-chat-with-your-data-solution-accelerator-3d01b35833f1f2e31347906017ef6773ac64a30fb0dc85306afc4a15c0f16af6-features -f /tmp/devcontainercli-root/container-features/0.56.2-1709566001811/Dockerfile.extended /tmp/devcontainercli-root/empty-folder
[144691 ms]     at atA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.348.0/dist/spec-node/devContainersSpecCLI.js:464:1260)
[144691 ms]     at yH (/root/.vscode-remote-containers/dist/dev-containers-cli-0.348.0/dist/spec-node/devContainersSpecCLI.js:464:1002)
[144691 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[144692 ms]     at async StA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.348.0/dist/spec-node/devContainersSpecCLI.js:481:3660)
[144692 ms]     at async ZC (/root/.vscode-remote-containers/dist/dev-containers-cli-0.348.0/dist/spec-node/devContainersSpecCLI.js:481:4775)
[144692 ms]     at async trA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.348.0/dist/spec-node/devContainersSpecCLI.js:614:11269)
[144692 ms]     at async erA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.348.0/dist/spec-node/devContainersSpecCLI.js:614:11010)
[144751 ms] Exit code 1
[144752 ms] Start: Run: docker rm -f b4e73356570c0884b831ceec96acadf9de627f61a43df9b5a80dd1d6d3fac793
[144757 ms] Command failed: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.348.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-1299b2a8-a2a0-4602-9afa-ba121bd179ca1709565897775 --workspace-folder /workspaces/chat-with-your-data-solution-accelerator --workspace-mount-consistency cached --id-label vsch.local.repository=https://github.com/azure-samples/chat-with-your-data-solution-accelerator --id-label vsch.local.repository.volume=chat-with-your-data-solution-accelerator-798e1b1c4cafef0adf40169ae01d318612925cda43582b440e22d12d9d1aa2a5 --id-label vsch.local.repository.folder=chat-with-your-data-solution-accelerator --id-label devcontainer.config_file=/workspaces/chat-with-your-data-solution-accelerator/.devcontainer/devcontainer.json --log-level debug --log-format json --config /workspaces/chat-with-your-data-solution-accelerator/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-4bb70ea7-d3a4-4e6d-9779-ceccf2e0665c.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=chat-with-your-data-solution-accelerator-798e1b1c4cafef0adf40169ae01d318612925cda43582b440e22d12d9d1aa2a5,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Ubuntu\mnt\wslg\runtime-dir\wayland-0,target=/tmp/vscode-wayland-d345e540-6467-4498-bf6a-7ab0cae62f89.sock --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root --terminal-columns 121 --terminal-rows 15
[144757 ms] Exit code 1
[148133 ms] Container server terminated (code: 137, signal: null).

**Comment by ross-p-smith** [comment]
Hi there, thanks for the info. I'm going to make a few assumptions here
1) You are running Windows and WSL
2) From a standard WSL Terminal you can successfully run something like `docker images` and get a valid list of images returned?
(This is all before you have touched this repo)

**Comment by sreedharguda** [comment]
> 1. Windows
Hi @ross-p-smith , Yes, docker is running on my windows machine and when i run the "Open in Dev Containers" in VS Code, am getting this error. Please help me how to resolve the issue or correct me if am running it differently. Thank you.

**Comment by ross-p-smith** [comment]
Thank you for bearing with me on this. I have just tried to click that button on the Readme and I get an error too. I think we could do much better getting this to work.
1) From a WSL terminal, go to a directory where you will keep your source code. (e.g. src). This will be a Linux location, not a Windows location
2) type `git clone https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator.git`
3) `cd` into the directory you have just cloned.
4) type `code .` to open the solution in WSL.
5) Ensure that you have the "Remote Development" extension installed in your vscode
6) The project will open and a pop should appear
![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/6254153/40d666e1-8468-4a18-ba4f-0f2fe89bf4ee)
- say yes
7) If you dont see that pop-up then click the >< in the bottom left corner and chose "Reopen in container"
![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/6254153/154e9364-817e-484a-aaa8-cabbdc8dad56)

**Comment by sreedharguda** [comment]
> Thank you for bearing with me on this. I have just tried to click that button on the Readme and I get an error too. I think we could do much better getting this to work.
> 
>     1. From a WSL terminal, go to a directory where you will keep your source code. (e.g. src). This will be a Linux location, not a Windows location
> 
>     2. type `git clone https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator.git`
> 
>     3. `cd` into the directory you have just cloned.
> 
>     4. type `code .` to open the solution in WSL.
> 
>     5. Ensure that you have the "Remote Development" extension installed in your vscode
> 
>     6. The project will open and a pop should appear
>        ![image](https://private-user-images.githubusercontent.com/6254153/309824523-40d666e1-8468-4a18-ba4f-0f2fe89bf4ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODYxMTMsIm5iZiI6MTcwOTc4NTgxMywicGF0aCI6Ii82MjU0MTUzLzMwOTgyNDUyMy00MGQ2NjZlMS04NDY4LTRhMTgtYmE0Zi0wZjJmZTg5YmY0ZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMDQzMDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTQ3NWVkMjE5ZjU0ZDg4NGNlOTMzZDRkYWJlNDc0ZTRhYzdhNTlkNjJlNzlkMGJlNmI4MmQ4MzA1OWUzZTRiNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vg-EvQ8YkJw2sPIKSn-b5OwwzczGUiX_IU3CRY9JD30)
> 
> 
>     * say yes
> 
> 
>     7. If you dont see that pop-up then click the >< in the bottom left corner and chose "Reopen in container"
>        ![image](https://private-user-images.githubusercontent.com/6254153/309824665-154e9364-817e-484a-aaa8-cabbdc8dad56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODYxMTMsIm5iZiI6MTcwOTc4NTgxMywicGF0aCI6Ii82MjU0MTUzLzMwOTgyNDY2NS0xNTRlOTM2NC04MTdlLTQ4NGEtYWFhOC1jYWJiZGM4ZGFkNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMDQzMDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDIwMDQ2NjhmMDE4NjQ1ZGVjYmY5OTA1ZTlhMjY4MTIxYjBkNjg1NDJiMTA0ZDVmY2YzYzhlMzQzOGEwODVmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EM4XuTg9SmOlit_ilYQdC52TyOzUNu_ggg7WMoPgJxI)

Hi @ross-p-smith  is there anyway we can deploy this without WSL. Please help me that path. Thank you.

**Comment by sreedharguda** [comment]
Hi @ross-p-smith,  I followed the article https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/NON_DEVCONTAINER_SETUP.md and able to create the resources in Azure. When i am trying to upload the document from Admin app service getting the below error. Could you please suggest on this error.

Traceback (most recent call last): File "/tmp/8dc3f4641e59718/pages/01_Ingest_Data.py", line 204, in <module> upload_file(bytes_data, up.name) File "/tmp/8dc3f4641e59718/pages/01_Ingest_Data.py", line 146, in upload_file env_helper.AZURE_KEY_VAULT_ENDPOINT, credential ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'EnvHelper' object has no attribute 'AZURE_KEY_VAULT_ENDPOINT'

**Comment by ross-p-smith** [comment]
Hi @sreedharguda - is this now the same as #387?

**Comment by sreedharguda** [comment]
> Hi @sreedharguda - is this now the same as #387?

Hi @ross-p-smith , Yes, thats true. I was able to resolve this issue by making the changes as mentioned #387.

**Comment by ross-p-smith** [comment]
Closing this based on the previous answer
