### ISSUE TITLE
Teams Bot isn't working - Failed to parse URL from undefined

### ISSUE THREAD

**Issue by chkrause** [Azure-Samples/chat-with-your-data-solution-accelerator#379]
Getting Error: Failed to parse URL from undefined

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Follow the instructions for Teams Extension: https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/TEAMS_EXTENSION.md

### Any log messages given by the failure
`Running with Message Activity.
TypeError: Failed to parse URL from undefinedat Object.fetch (node:internal/deps/undici/undici:11118:11)at process.processTicksAndRejections (node:internal/process/task_queues:95:5)at async Array.<anonymous> (C:\home\site\wwwroot\lib\teamsBot.js:35:38) {[cause]: TypeError [ERR_INVALID_URL]: Invalid URLat new NodeError (node:internal/errors:393:5)
at URL.onParseError (node:internal/url:565:9)at new URL (node:internal/url:645:5)at new Request (node:internal/deps/undici/undici:9472:25)at Agent.fetch2 (node:internal/deps/undici/undici:10291:25)at Object.fetch (node:internal/deps/undici/undici:11116:28)at fetch (node:internal/process/pre_execution:216:25)at Array.<anonymous> (C:\home\site\wwwroot\lib\teamsBot.js:35:44)at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {input: 'undefined',code: 'ERR_INVALID_URL'}}(node:5528) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
2024-03-04T16:42:55  No new trace in the past 1 min(s).`

**Comment by chkrause** [comment]
I figured out that there are two environment variables hasn't been configured.
One in the function app: 
- here the APPINSIGHTS_CONNECTION_STRING was missing
One in Bot web app:
- here the AZURE_FUNCTION_URL was missing

after seting it manually via azure portal the teams extension is working now

**Comment by ross-p-smith** [comment]
Thank you ever so much @chkrause - if you can put together a small PR - I'll happily approve! Thanks for finding this

**Comment by ross-p-smith** [comment]
@chkrause - can we close this one? Thanks for your contribution

**Comment by chkrause** [comment]
Sure
